Weighted endpoints RPCClient
skynetcapital/solanaj pull request #78
Opened 2021-06-24 03:40 UTC by cryptogosu

Added ability to have a weighted switch between different urls.

2021-06-24 20:38 UTC, busligisti commented on src/main/java/org/p2p/solanaj/rpc/WeightedCluster.java
> +@Data
Are all the methods generated by `@Data` necessary here? Only the getters and the all args constructor are used so far. Please consider this in the WeightedEndpoint class too.

2021-06-25 01:18 UTC, skynetcapital commented on src/main/java/org/p2p/solanaj/rpc/WeightedCluster.java
> +@Data
> Are all the methods generated by `@Data` necessary here? Only the getters and the all args constructor are used so far. Please consider this in the WeightedEndpoint class too.

+1, will merge when addressed + the small docs

2021-06-25 01:19 UTC, skynetcapital requested changes
See comment by @busligisti on potential requested change, plus the docs mentioned in Discord.

2021-06-25 07:25 UTC, busligisti commented on src/main/java/org/p2p/solanaj/rpc/RpcClient.java
> +            } else if (randomNumber >= currentNumber && randomNumber < currentNumber + endpoint.getWeight()) {
I just noticed this one. Do we need this else-if branch? The same code is executed inside both this and the else branch.

2021-06-25 16:34 UTC, cryptogosu commented on src/main/java/org/p2p/solanaj/rpc/RpcClient.java
> +            } else if (randomNumber >= currentNumber && randomNumber < currentNumber + endpoint.getWeight()) {
Updated my else if to use `randomNumber <= currentNumber + endpoint.getWeight()` to remove the last `else`

2021-06-25 16:35 UTC, cryptogosu commented on src/main/java/org/p2p/solanaj/rpc/WeightedCluster.java
> +@Data
Updated to use `@Getter`, `@Setter`, `@AllArgsConstructor`, and `@NoArgsConstructor`. Added both the last two to give more flexibility to developers on how they create objects.

Usually `@Data` is recommended if the state of the object may change in the future. I expect these objects will be static though

2021-06-25 16:55 UTC, skynetcapital commented
LGTM, thanks!

2021-06-25 16:55 UTC, merged